# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: '%kernel.default_locale%'
    orm:
        # Activate the extensions you want
        default:
            translatable: true
            timestampable: true
            blameable: false
            sluggable: true
            tree: false
            loggable: true
            sortable: true
            softdeleteable: false
            uploadable: false
            reference_integrity: false
